### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-dusseldorf#25]

**Comment by SSirjes** [comment]
- [x] Front page - **main styles secondary font don't apply to custom made button** (made with text toolbar button) 

Left side button is custom. Right side is form button
![screen_shot_2016-04-22_at_10_24_41](https://cloud.githubusercontent.com/assets/13623224/14734747/385d22e2-0875-11e6-94f6-b777f5b94314.png)

**Comment by SSirjes** [comment]
- [x] **Site title has default some opacity**

Change under sidebar title color to wite (#fff). After that, you can see, that site title has opacity
![screen_shot_2016-04-22_at_11_08_26](https://cloud.githubusercontent.com/assets/13623224/14735747/7b31a65a-087b-11e6-8fa4-ded3416cfeff.png)
- [x] **Content block default text ("Go on, start typing" is not visible) do not stand out** if main styles primary color is changed white

Video: http://recordit.co/BE9i5cHkdT

**Comment by SSirjes** [comment]
- [x] **Table dotted and dashed right side border style will be not displayed in preview mode**. Happens in Firefox
  ![table](https://cloud.githubusercontent.com/assets/13623224/14741986/8062252e-08a2-11e6-938a-270fda819f7b.jpg)

**Henn:** removed dotted and dashed from selection

**Comment by SSirjes** [comment]
- [x] **Front page and content text alignment bug**

If content text alignment is changed to center or right, then front page two equal boxes content is incorrectly positioned. Video, what happens: http://recordit.co/ZLopP6zlmv

**Comment by SSirjes** [comment]
III round testing
- [x]  **Custom button needs line height**

![screen_shot_2016-04-26_at_20_17_04](https://cloud.githubusercontent.com/assets/13623224/14827623/f032fe72-0beb-11e6-8834-aaeb90bbe2ba.png)
- [ ] Main styles secondary color will changes partially form field background color. Also it will change custom button hover color
  Video: http://recordit.co/jnRY8yMIPo
